version: '3.8'
services:

  elrond:
    container_name: elrond_1
    restart: always
    volumes:
      - ./config/:/opt/app/config/
      - ./db/:/opt/app/db/
#      - ./logs/:/opt/app/logs/
#      - ./stats/:/opt/app/stats/
#    ports:
#      - '127.0.0.1:8080:8080'
#      - '127.0.0.1:38303:38303'
    build:
      context: .build
      args:
        ELROND_VERSION: v1.0.16
        CONFIG_VERSION: testnet-1016
